using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using TicTacTec.TA.Library;
using static TicTacTec.TA.Library.Core;

public class Integration
{
    public async Task<dynamic> Macd(IDictionary<string, object> value)
    {
        var inReal = ConvertToArray<double>("inReal", value);
        var outMACD = ConvertToArray<double>("outMACD", value);
        var outMACDSignal = ConvertToArray<double>("outMACDSignal", value);
        var outMACDHist = ConvertToArray<double>("outMACDHist", value);

        int outBegIdx;
        int outNBElement;
        var result = Core.Macd((int)value["startIdx"], (int)value["endIdx"], inReal, (int)value["optInFastPeriod"], (int)value["optInSlowPeriod"], (int)value["optInSignalPeriod"], out outBegIdx, out outNBElement, outMACD, outMACDSignal, outMACDHist);

        return await Task.FromResult(new
        {
            outBegIdx,
            outNBElement
        });
    }

    private static T[] ConvertToArray<T>(string name, IDictionary<string, object> value)
    {
        var list = new List<T>();
        foreach (var item in (object[])value[name])
        {
            list.Add((T)Convert.ChangeType(item, typeof(T)));
        }

        return list.ToArray();
    }

    //public static RetCode Acos(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Acos(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int AcosLookback();
    //public static RetCode Ad(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, float[] inVolume, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Ad(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, double[] inVolume, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Add(int startIdx, int endIdx, double[] inReal0, double[] inReal1, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Add(int startIdx, int endIdx, float[] inReal0, float[] inReal1, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int AddLookback();
    //public static int AdLookback();
    //public static RetCode AdOsc(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, double[] inVolume, int optInFastPeriod, int optInSlowPeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode AdOsc(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, float[] inVolume, int optInFastPeriod, int optInSlowPeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int AdOscLookback(int optInFastPeriod, int optInSlowPeriod);
    //public static RetCode Adx(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Adx(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int AdxLookback(int optInTimePeriod);
    //public static RetCode Adxr(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Adxr(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int AdxrLookback(int optInTimePeriod);
    //public static RetCode Apo(int startIdx, int endIdx, float[] inReal, int optInFastPeriod, int optInSlowPeriod, MAType optInMAType, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Apo(int startIdx, int endIdx, double[] inReal, int optInFastPeriod, int optInSlowPeriod, MAType optInMAType, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int ApoLookback(int optInFastPeriod, int optInSlowPeriod, MAType optInMAType);
    //public static RetCode Aroon(int startIdx, int endIdx, float[] inHigh, float[] inLow, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outAroonDown, double[] outAroonUp);
    //public static RetCode Aroon(int startIdx, int endIdx, double[] inHigh, double[] inLow, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outAroonDown, double[] outAroonUp);
    //public static int AroonLookback(int optInTimePeriod);
    //public static RetCode AroonOsc(int startIdx, int endIdx, float[] inHigh, float[] inLow, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode AroonOsc(int startIdx, int endIdx, double[] inHigh, double[] inLow, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int AroonOscLookback(int optInTimePeriod);
    //public static RetCode Asin(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Asin(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int AsinLookback();
    //public static RetCode Atan(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Atan(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int AtanLookback();
    //public static RetCode Atr(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Atr(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int AtrLookback(int optInTimePeriod);
    //public static RetCode AvgPrice(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode AvgPrice(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int AvgPriceLookback();
    //public static RetCode Bbands(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, double optInNbDevUp, double optInNbDevDn, MAType optInMAType, out int outBegIdx, out int outNBElement, double[] outRealUpperBand, double[] outRealMiddleBand, double[] outRealLowerBand);
    //public static RetCode Bbands(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, double optInNbDevUp, double optInNbDevDn, MAType optInMAType, out int outBegIdx, out int outNBElement, double[] outRealUpperBand, double[] outRealMiddleBand, double[] outRealLowerBand);
    //public static int BbandsLookback(int optInTimePeriod, double optInNbDevUp, double optInNbDevDn, MAType optInMAType);
    //public static RetCode Beta(int startIdx, int endIdx, float[] inReal0, float[] inReal1, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Beta(int startIdx, int endIdx, double[] inReal0, double[] inReal1, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int BetaLookback(int optInTimePeriod);
    //public static RetCode Bop(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Bop(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int BopLookback();
    //public static RetCode Cci(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Cci(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int CciLookback(int optInTimePeriod);
    //public static RetCode Cdl2Crows(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode Cdl2Crows(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int Cdl2CrowsLookback();
    //public static RetCode Cdl3BlackCrows(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode Cdl3BlackCrows(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int Cdl3BlackCrowsLookback();
    //public static RetCode Cdl3Inside(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode Cdl3Inside(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int Cdl3InsideLookback();
    //public static RetCode Cdl3LineStrike(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode Cdl3LineStrike(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int Cdl3LineStrikeLookback();
    //public static RetCode Cdl3Outside(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode Cdl3Outside(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int Cdl3OutsideLookback();
    //public static RetCode Cdl3StarsInSouth(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode Cdl3StarsInSouth(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int Cdl3StarsInSouthLookback();
    //public static RetCode Cdl3WhiteSoldiers(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode Cdl3WhiteSoldiers(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int Cdl3WhiteSoldiersLookback();
    //public static RetCode CdlAbandonedBaby(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlAbandonedBaby(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlAbandonedBabyLookback(double optInPenetration);
    //public static RetCode CdlAdvanceBlock(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlAdvanceBlock(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlAdvanceBlockLookback();
    //public static RetCode CdlBeltHold(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlBeltHold(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlBeltHoldLookback();
    //public static RetCode CdlBreakaway(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlBreakaway(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlBreakawayLookback();
    //public static RetCode CdlClosingMarubozu(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlClosingMarubozu(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlClosingMarubozuLookback();
    //public static RetCode CdlConcealBabysWall(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlConcealBabysWall(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlConcealBabysWallLookback();
    //public static RetCode CdlCounterAttack(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlCounterAttack(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlCounterAttackLookback();
    //public static RetCode CdlDarkCloudCover(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlDarkCloudCover(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlDarkCloudCoverLookback(double optInPenetration);
    //public static RetCode CdlDoji(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlDoji(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlDojiLookback();
    //public static RetCode CdlDojiStar(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlDojiStar(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlDojiStarLookback();
    //public static RetCode CdlDragonflyDoji(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlDragonflyDoji(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlDragonflyDojiLookback();
    //public static RetCode CdlEngulfing(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlEngulfing(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlEngulfingLookback();
    //public static RetCode CdlEveningDojiStar(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlEveningDojiStar(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlEveningDojiStarLookback(double optInPenetration);
    //public static RetCode CdlEveningStar(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlEveningStar(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlEveningStarLookback(double optInPenetration);
    //public static RetCode CdlGapSideSideWhite(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlGapSideSideWhite(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlGapSideSideWhiteLookback();
    //public static RetCode CdlGravestoneDoji(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlGravestoneDoji(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlGravestoneDojiLookback();
    //public static RetCode CdlHammer(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlHammer(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlHammerLookback();
    //public static RetCode CdlHangingMan(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlHangingMan(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlHangingManLookback();
    //public static RetCode CdlHarami(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlHarami(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlHaramiCross(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlHaramiCross(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlHaramiCrossLookback();
    //public static int CdlHaramiLookback();
    //public static RetCode CdlHignWave(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlHignWave(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlHignWaveLookback();
    //public static RetCode CdlHikkake(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlHikkake(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlHikkakeLookback();
    //public static RetCode CdlHikkakeMod(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlHikkakeMod(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlHikkakeModLookback();
    //public static RetCode CdlHomingPigeon(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlHomingPigeon(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlHomingPigeonLookback();
    //public static RetCode CdlIdentical3Crows(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlIdentical3Crows(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlIdentical3CrowsLookback();
    //public static RetCode CdlInNeck(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlInNeck(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlInNeckLookback();
    //public static RetCode CdlInvertedHammer(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlInvertedHammer(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlInvertedHammerLookback();
    //public static RetCode CdlKicking(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlKicking(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlKickingByLength(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlKickingByLength(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlKickingByLengthLookback();
    //public static int CdlKickingLookback();
    //public static RetCode CdlLadderBottom(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlLadderBottom(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlLadderBottomLookback();
    //public static RetCode CdlLongLeggedDoji(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlLongLeggedDoji(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlLongLeggedDojiLookback();
    //public static RetCode CdlLongLine(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlLongLine(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlLongLineLookback();
    //public static RetCode CdlMarubozu(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlMarubozu(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlMarubozuLookback();
    //public static RetCode CdlMatchingLow(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlMatchingLow(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlMatchingLowLookback();
    //public static RetCode CdlMatHold(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlMatHold(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlMatHoldLookback(double optInPenetration);
    //public static RetCode CdlMorningDojiStar(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlMorningDojiStar(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlMorningDojiStarLookback(double optInPenetration);
    //public static RetCode CdlMorningStar(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlMorningStar(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, double optInPenetration, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlMorningStarLookback(double optInPenetration);
    //public static RetCode CdlOnNeck(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlOnNeck(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlOnNeckLookback();
    //public static RetCode CdlPiercing(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlPiercing(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlPiercingLookback();
    //public static RetCode CdlRickshawMan(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlRickshawMan(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlRickshawManLookback();
    //public static RetCode CdlRiseFall3Methods(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlRiseFall3Methods(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlRiseFall3MethodsLookback();
    //public static RetCode CdlSeperatingLines(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlSeperatingLines(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlSeperatingLinesLookback();
    //public static RetCode CdlShootingStar(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlShootingStar(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlShootingStarLookback();
    //public static RetCode CdlShortLine(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlShortLine(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlShortLineLookback();
    //public static RetCode CdlSpinningTop(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlSpinningTop(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlSpinningTopLookback();
    //public static RetCode CdlStalledPattern(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlStalledPattern(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlStalledPatternLookback();
    //public static RetCode CdlStickSandwhich(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlStickSandwhich(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlStickSandwhichLookback();
    //public static RetCode CdlTakuri(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlTakuri(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlTakuriLookback();
    //public static RetCode CdlTasukiGap(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlTasukiGap(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlTasukiGapLookback();
    //public static RetCode CdlThrusting(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlThrusting(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlThrustingLookback();
    //public static RetCode CdlTristar(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlTristar(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlTristarLookback();
    //public static RetCode CdlUnique3River(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlUnique3River(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlUnique3RiverLookback();
    //public static RetCode CdlUpsideGap2Crows(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlUpsideGap2Crows(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlUpsideGap2CrowsLookback();
    //public static RetCode CdlXSideGap3Methods(int startIdx, int endIdx, double[] inOpen, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode CdlXSideGap3Methods(int startIdx, int endIdx, float[] inOpen, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int CdlXSideGap3MethodsLookback();
    //public static RetCode Ceil(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Ceil(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int CeilLookback();
    //public static RetCode Cmo(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Cmo(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int CmoLookback(int optInTimePeriod);
    //public static RetCode Correl(int startIdx, int endIdx, double[] inReal0, double[] inReal1, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Correl(int startIdx, int endIdx, float[] inReal0, float[] inReal1, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int CorrelLookback(int optInTimePeriod);
    //public static RetCode Cos(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Cos(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Cosh(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Cosh(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int CoshLookback();
    //public static int CosLookback();
    //public static RetCode Dema(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Dema(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int DemaLookback(int optInTimePeriod);
    //public static RetCode Div(int startIdx, int endIdx, float[] inReal0, float[] inReal1, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Div(int startIdx, int endIdx, double[] inReal0, double[] inReal1, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int DivLookback();
    //public static RetCode Dx(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Dx(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int DxLookback(int optInTimePeriod);
    //public static RetCode Ema(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Ema(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int EmaLookback(int optInTimePeriod);
    //public static RetCode Exp(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Exp(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int ExpLookback();
    //public static RetCode Floor(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Floor(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int FloorLookback();
    //public static Compatibility GetCompatibility();
    //public static uint GetUnstablePeriod(FuncUnstId id);
    //public static RetCode HtDcPeriod(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode HtDcPeriod(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int HtDcPeriodLookback();
    //public static RetCode HtDcPhase(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode HtDcPhase(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int HtDcPhaseLookback();
    //public static RetCode HtPhasor(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outInPhase, double[] outQuadrature);
    //public static RetCode HtPhasor(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outInPhase, double[] outQuadrature);
    //public static int HtPhasorLookback();
    //public static RetCode HtSine(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outSine, double[] outLeadSine);
    //public static RetCode HtSine(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outSine, double[] outLeadSine);
    //public static int HtSineLookback();
    //public static RetCode HtTrendline(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode HtTrendline(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int HtTrendlineLookback();
    //public static RetCode HtTrendMode(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode HtTrendMode(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int HtTrendModeLookback();
    //public static RetCode Kama(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Kama(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int KamaLookback(int optInTimePeriod);
    //public static RetCode LinearReg(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode LinearReg(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode LinearRegAngle(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode LinearRegAngle(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int LinearRegAngleLookback(int optInTimePeriod);
    //public static RetCode LinearRegIntercept(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode LinearRegIntercept(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int LinearRegInterceptLookback(int optInTimePeriod);
    //public static int LinearRegLookback(int optInTimePeriod);
    //public static RetCode LinearRegSlope(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode LinearRegSlope(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int LinearRegSlopeLookback(int optInTimePeriod);
    //public static RetCode Ln(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Ln(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int LnLookback();
    //public static RetCode Log10(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Log10(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int Log10Lookback();
    //public static RetCode Macd(int startIdx, int endIdx, double[] inReal, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, out int outBegIdx, out int outNBElement, double[] outMACD, double[] outMACDSignal, double[] outMACDHist);
    //public static RetCode Macd(int startIdx, int endIdx, float[] inReal, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, out int outBegIdx, out int outNBElement, double[] outMACD, double[] outMACDSignal, double[] outMACDHist);
    //public static RetCode MacdExt(int startIdx, int endIdx, double[] inReal, int optInFastPeriod, MAType optInFastMAType, int optInSlowPeriod, MAType optInSlowMAType, int optInSignalPeriod, MAType optInSignalMAType, out int outBegIdx, out int outNBElement, double[] outMACD, double[] outMACDSignal, double[] outMACDHist);
    //public static RetCode MacdExt(int startIdx, int endIdx, float[] inReal, int optInFastPeriod, MAType optInFastMAType, int optInSlowPeriod, MAType optInSlowMAType, int optInSignalPeriod, MAType optInSignalMAType, out int outBegIdx, out int outNBElement, double[] outMACD, double[] outMACDSignal, double[] outMACDHist);
    //public static int MacdExtLookback(int optInFastPeriod, MAType optInFastMAType, int optInSlowPeriod, MAType optInSlowMAType, int optInSignalPeriod, MAType optInSignalMAType);
    //public static RetCode MacdFix(int startIdx, int endIdx, float[] inReal, int optInSignalPeriod, out int outBegIdx, out int outNBElement, double[] outMACD, double[] outMACDSignal, double[] outMACDHist);
    //public static RetCode MacdFix(int startIdx, int endIdx, double[] inReal, int optInSignalPeriod, out int outBegIdx, out int outNBElement, double[] outMACD, double[] outMACDSignal, double[] outMACDHist);
    //public static int MacdFixLookback(int optInSignalPeriod);
    //public static int MacdLookback(int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod);
    //public static RetCode Mama(int startIdx, int endIdx, float[] inReal, double optInFastLimit, double optInSlowLimit, out int outBegIdx, out int outNBElement, double[] outMAMA, double[] outFAMA);
    //public static RetCode Mama(int startIdx, int endIdx, double[] inReal, double optInFastLimit, double optInSlowLimit, out int outBegIdx, out int outNBElement, double[] outMAMA, double[] outFAMA);
    //public static int MamaLookback(double optInFastLimit, double optInSlowLimit);
    //public static RetCode Max(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Max(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode MaxIndex(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode MaxIndex(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int MaxIndexLookback(int optInTimePeriod);
    //public static int MaxLookback(int optInTimePeriod);
    //public static RetCode MedPrice(int startIdx, int endIdx, float[] inHigh, float[] inLow, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode MedPrice(int startIdx, int endIdx, double[] inHigh, double[] inLow, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int MedPriceLookback();
    //public static RetCode Mfi(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, double[] inVolume, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Mfi(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, float[] inVolume, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int MfiLookback(int optInTimePeriod);
    //public static RetCode MidPoint(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode MidPoint(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int MidPointLookback(int optInTimePeriod);
    //public static RetCode MidPrice(int startIdx, int endIdx, float[] inHigh, float[] inLow, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode MidPrice(int startIdx, int endIdx, double[] inHigh, double[] inLow, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int MidPriceLookback(int optInTimePeriod);
    //public static RetCode Min(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Min(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode MinIndex(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static RetCode MinIndex(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, int[] outInteger);
    //public static int MinIndexLookback(int optInTimePeriod);
    //public static int MinLookback(int optInTimePeriod);
    //public static RetCode MinMax(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outMin, double[] outMax);
    //public static RetCode MinMax(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outMin, double[] outMax);
    //public static RetCode MinMaxIndex(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, int[] outMinIdx, int[] outMaxIdx);
    //public static RetCode MinMaxIndex(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, int[] outMinIdx, int[] outMaxIdx);
    //public static int MinMaxIndexLookback(int optInTimePeriod);
    //public static int MinMaxLookback(int optInTimePeriod);
    //public static RetCode MinusDI(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode MinusDI(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int MinusDILookback(int optInTimePeriod);
    //public static RetCode MinusDM(int startIdx, int endIdx, double[] inHigh, double[] inLow, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode MinusDM(int startIdx, int endIdx, float[] inHigh, float[] inLow, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int MinusDMLookback(int optInTimePeriod);
    //public static RetCode Mom(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Mom(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int MomLookback(int optInTimePeriod);
    //public static RetCode MovingAverage(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, MAType optInMAType, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode MovingAverage(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, MAType optInMAType, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int MovingAverageLookback(int optInTimePeriod, MAType optInMAType);
    //public static RetCode MovingAverageVariablePeriod(int startIdx, int endIdx, float[] inReal, float[] inPeriods, int optInMinPeriod, int optInMaxPeriod, MAType optInMAType, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode MovingAverageVariablePeriod(int startIdx, int endIdx, double[] inReal, double[] inPeriods, int optInMinPeriod, int optInMaxPeriod, MAType optInMAType, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int MovingAverageVariablePeriodLookback(int optInMinPeriod, int optInMaxPeriod, MAType optInMAType);
    //public static RetCode Mult(int startIdx, int endIdx, float[] inReal0, float[] inReal1, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Mult(int startIdx, int endIdx, double[] inReal0, double[] inReal1, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int MultLookback();
    //public static RetCode Natr(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Natr(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int NatrLookback(int optInTimePeriod);
    //public static RetCode Obv(int startIdx, int endIdx, float[] inReal, float[] inVolume, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Obv(int startIdx, int endIdx, double[] inReal, double[] inVolume, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int ObvLookback();
    //public static RetCode PlusDI(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode PlusDI(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int PlusDILookback(int optInTimePeriod);
    //public static RetCode PlusDM(int startIdx, int endIdx, double[] inHigh, double[] inLow, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode PlusDM(int startIdx, int endIdx, float[] inHigh, float[] inLow, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int PlusDMLookback(int optInTimePeriod);
    //public static RetCode Ppo(int startIdx, int endIdx, float[] inReal, int optInFastPeriod, int optInSlowPeriod, MAType optInMAType, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Ppo(int startIdx, int endIdx, double[] inReal, int optInFastPeriod, int optInSlowPeriod, MAType optInMAType, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int PpoLookback(int optInFastPeriod, int optInSlowPeriod, MAType optInMAType);
    //public static RetCode RestoreCandleDefaultSettings(CandleSettingType settingType);
    //public static RetCode Roc(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Roc(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int RocLookback(int optInTimePeriod);
    //public static RetCode RocP(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode RocP(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int RocPLookback(int optInTimePeriod);
    //public static RetCode RocR(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode RocR(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode RocR100(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode RocR100(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int RocR100Lookback(int optInTimePeriod);
    //public static int RocRLookback(int optInTimePeriod);
    //public static RetCode Rsi(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Rsi(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int RsiLookback(int optInTimePeriod);
    //public static RetCode Sar(int startIdx, int endIdx, double[] inHigh, double[] inLow, double optInAcceleration, double optInMaximum, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Sar(int startIdx, int endIdx, float[] inHigh, float[] inLow, double optInAcceleration, double optInMaximum, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode SarExt(int startIdx, int endIdx, double[] inHigh, double[] inLow, double optInStartValue, double optInOffsetOnReverse, double optInAccelerationInitLong, double optInAccelerationLong, double optInAccelerationMaxLong, double optInAccelerationInitShort, double optInAccelerationShort, double optInAccelerationMaxShort, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode SarExt(int startIdx, int endIdx, float[] inHigh, float[] inLow, double optInStartValue, double optInOffsetOnReverse, double optInAccelerationInitLong, double optInAccelerationLong, double optInAccelerationMaxLong, double optInAccelerationInitShort, double optInAccelerationShort, double optInAccelerationMaxShort, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int SarExtLookback(double optInStartValue, double optInOffsetOnReverse, double optInAccelerationInitLong, double optInAccelerationLong, double optInAccelerationMaxLong, double optInAccelerationInitShort, double optInAccelerationShort, double optInAccelerationMaxShort);
    //public static int SarLookback(double optInAcceleration, double optInMaximum);
    //public static RetCode SetCandleSettings(CandleSettingType settingType, RangeType rangeType, int avgPeriod, double factor);
    //public static RetCode SetCompatibility(Compatibility value);
    //public static RetCode SetUnstablePeriod(FuncUnstId id, uint unstablePeriod);
    //public static RetCode Sin(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Sin(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Sinh(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Sinh(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int SinhLookback();
    //public static int SinLookback();
    //public static RetCode Sma(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Sma(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int SmaLookback(int optInTimePeriod);
    //public static RetCode Sqrt(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Sqrt(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int SqrtLookback();
    //public static RetCode StdDev(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, double optInNbDev, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode StdDev(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, double optInNbDev, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int StdDevLookback(int optInTimePeriod, double optInNbDev);
    //public static RetCode Stoch(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, int optInFastK_Period, int optInSlowK_Period, MAType optInSlowK_MAType, int optInSlowD_Period, MAType optInSlowD_MAType, out int outBegIdx, out int outNBElement, double[] outSlowK, double[] outSlowD);
    //public static RetCode Stoch(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, int optInFastK_Period, int optInSlowK_Period, MAType optInSlowK_MAType, int optInSlowD_Period, MAType optInSlowD_MAType, out int outBegIdx, out int outNBElement, double[] outSlowK, double[] outSlowD);
    //public static RetCode StochF(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, int optInFastK_Period, int optInFastD_Period, MAType optInFastD_MAType, out int outBegIdx, out int outNBElement, double[] outFastK, double[] outFastD);
    //public static RetCode StochF(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, int optInFastK_Period, int optInFastD_Period, MAType optInFastD_MAType, out int outBegIdx, out int outNBElement, double[] outFastK, double[] outFastD);
    //public static int StochFLookback(int optInFastK_Period, int optInFastD_Period, MAType optInFastD_MAType);
    //public static int StochLookback(int optInFastK_Period, int optInSlowK_Period, MAType optInSlowK_MAType, int optInSlowD_Period, MAType optInSlowD_MAType);
    //public static RetCode StochRsi(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, int optInFastK_Period, int optInFastD_Period, MAType optInFastD_MAType, out int outBegIdx, out int outNBElement, double[] outFastK, double[] outFastD);
    //public static RetCode StochRsi(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, int optInFastK_Period, int optInFastD_Period, MAType optInFastD_MAType, out int outBegIdx, out int outNBElement, double[] outFastK, double[] outFastD);
    //public static int StochRsiLookback(int optInTimePeriod, int optInFastK_Period, int optInFastD_Period, MAType optInFastD_MAType);
    //public static RetCode Sub(int startIdx, int endIdx, double[] inReal0, double[] inReal1, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Sub(int startIdx, int endIdx, float[] inReal0, float[] inReal1, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int SubLookback();
    //public static RetCode Sum(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Sum(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int SumLookback(int optInTimePeriod);
    //public static RetCode T3(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, double optInVFactor, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode T3(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, double optInVFactor, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int T3Lookback(int optInTimePeriod, double optInVFactor);
    //public static RetCode Tan(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Tan(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Tanh(int startIdx, int endIdx, float[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Tanh(int startIdx, int endIdx, double[] inReal, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int TanhLookback();
    //public static int TanLookback();
    //public static RetCode Tema(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Tema(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int TemaLookback(int optInTimePeriod);
    //public static RetCode Trima(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Trima(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int TrimaLookback(int optInTimePeriod);
    //public static RetCode Trix(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Trix(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int TrixLookback(int optInTimePeriod);
    //public static RetCode TrueRange(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode TrueRange(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int TrueRangeLookback();
    //public static RetCode Tsf(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Tsf(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int TsfLookback(int optInTimePeriod);
    //public static RetCode TypPrice(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode TypPrice(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int TypPriceLookback();
    //public static RetCode UltOsc(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, int optInTimePeriod1, int optInTimePeriod2, int optInTimePeriod3, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode UltOsc(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, int optInTimePeriod1, int optInTimePeriod2, int optInTimePeriod3, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int UltOscLookback(int optInTimePeriod1, int optInTimePeriod2, int optInTimePeriod3);
    //public static RetCode Variance(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, double optInNbDev, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Variance(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, double optInNbDev, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int VarianceLookback(int optInTimePeriod, double optInNbDev);
    //public static RetCode WclPrice(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode WclPrice(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int WclPriceLookback();
    //public static RetCode WillR(int startIdx, int endIdx, float[] inHigh, float[] inLow, float[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode WillR(int startIdx, int endIdx, double[] inHigh, double[] inLow, double[] inClose, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int WillRLookback(int optInTimePeriod);
    //public static RetCode Wma(int startIdx, int endIdx, float[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static RetCode Wma(int startIdx, int endIdx, double[] inReal, int optInTimePeriod, out int outBegIdx, out int outNBElement, double[] outReal);
    //public static int WmaLookback(int optInTimePeriod);



}
